on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        version: [ 0.16.0, 0.18.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          dfx-version: ${{ matrix.version }}
          install-moc: true
          vessel-version: 0.7.0
          pocket-ic-version: release-2024-04-24_23-01-base
      - name: Test Versions
        run: |
          dfx --version
          moc --version
          vessel --version
          pocket-ic --version
      - name: Test Cache
        run: |
          dfx new test --type=motoko --no-frontend
          mv test/dfx.json .
          dfx start --background
          dfx canister create test_backend
          dfx stop

          vessel init
          vessel sources
