on: [ push ]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dfx-version: 0.13.1
          install-moc: true
          vessel-version: 0.6.5
      - run: |
          dfx --version
          moc --version
          vessel --version
